[tool.semantic_release]
version_source = "tag"
commit_parser = "angular"
tag_format = "v{version}"
upload_to_release = false
build_command = false

[tool.semantic_release.changelog]
changelog_file = "CHANGELOG.md"

[tool.semantic_release.commit_author]
name = "github-actions[bot]"
email = "github-actions[bot]@users.noreply.github.com"
